### ISSUE TITLE
Bug: Helix Swarm module should support SSO logins

### ISSUE THREAD

**Issue by keith-miller** [aws-games/cloud-game-development-toolkit#294]
### Expected Behaviour

There should be an option in `helix-swarm` module to enable SSO when creating the service.

### Current Behaviour

There is no option currently. 

### Possible Solution

To enable, you have to add the following line to the `config.php` file:

```php
        'p4' => array(
            // ...
            'sso'       => 'enabled', 
         ),
```

### Steps to Reproduce

Install the `helix-swarm` module and load it up in the browser. 

### Cloud Game Development Toolkit version

latest

**Comment by henrykie** [comment]
I would also like to see Perforce update the container to support this as an environment variable.

**Comment by keith-miller** [comment]
Agreed, that would be the cleanest solution

**Comment by henrykie** [comment]
Looked into this further. Documenting here.

The Helix Swarm docker container leverages a shell script `configure-swarm.sh` for creation of `config.php` programmatically off of environment variables:

```
configure_swarm()
{
    local php_config_export
    local new_config

    echo "Configuring Swarm installation..."
    # Use PHP to construct initial new values, and read in existing config.php
    # Anything we declare will "win", preserving other existing settings.
    # shellcheck disable=SC2155
    local php_config_export="$($PHP -r "\
        \$config = array(
            'environment'   => array(
            'hostname'  => '$SWARM_HOST',
        ),
        'p4' => array(
            'port'      => '$P4PORT',
            'user'      => '$SWARM_USER',
            'password'  => '$SWARM_PASSWD',
        ),
    );
if (strlen('$EMAIL_HOST')) {
    \$config['mail'] = array(
        'transport' => array(
          'host' => '$EMAIL_HOST',
        ),
    );
}
file_exists('$SWARM_CONFIG') && is_array(\$old_config = include '$SWARM_CONFIG' ) && \$config = array_replace_recursive(\$old_config, \$config);
unset(\$config['environment']['base_url']);
if (strlen('$BASE_URL')) {
    \$config['environment']['base_url'] = '/' . '$BASE_URL';
}
var_export(\$config);")"
    local new_config="\
<?php
/* WARNING: The contents of this file is cached by Swarm. Changes to
 * it will not be picked up until the cached versions are removed.
 * See the documentation on the 'Swarm config cache'.
 */
return $php_config_export;"
```

Of note, the shell script states: "Anything we declare will "win", preserving other existing settings."

The approach will be the creation of a `config.php` file prior to swarm startup that can be used to inject other settings such as `sso => enabled`.
