### ISSUE TITLE
Feature request: Helix Swarm should have ECS Exec enabled for debugging purposes

### ISSUE THREAD

**Issue by keith-miller** [aws-games/cloud-game-development-toolkit#295]
### Use case

Sometimes it helps to be able to access the Swarm container when running to debug issues. 

### Solution/User Experience

Add  `enable_execute_command = true` to the `aws_ecs_service.helix_swarm_service` resource in the `helix-swarm` module.

**Comment by henrykie** [comment]
Or just have a debug option that flags a bunch of the existing variables (deletion protection on ALBs, access logs, etc...)

I'll take this on.
