### ISSUE TITLE
Feature request: Support setting Unicode mode during `p4_configure.sh` run

### ISSUE THREAD

**Issue by keith-miller** [aws-games/cloud-game-development-toolkit#301]
### Use case

So, to enable Unicode support in Helix Core the following command is usually run during the `p4_configure` step:

```shelll
p4d -xi -r <server_root>
```

It would be great to have this added to the `p4_configure.sh` setup script so that the Perforce server is ready to go before use. 

### Solution/User Experience

As stated above, the command can be added to `p4_configure.sh`

**Comment by henrykie** [comment]
From my reading the only way to set this is after the service has started. We run p4d as a systemd managed service, and this may require more extensive modification. @GrzesiekO, any ideas?

**Comment by GrzesiekO** [comment]
Adding parameters with the systemctl service and p4d init scripts will require rebuilding or altering the later ones to add the -xi flag. 
Working on this to make sure nothing breaks in a service itself.

**Comment by GrzesiekO** [comment]
This issue is resolved in PR #378 unicode has been added to p4_configure.sh now it has to be provided as parameter.
