### ISSUE TITLE
Feature request: Container support for Assets

### ISSUE THREAD

**Issue by kylesomers** [aws-games/cloud-game-development-toolkit#55]
### Use case

Currently the Assets directory contains Packer templates for building AMIs. Game developers that want to standardize their workflows on containers may want the toolkit to provide a way to deploy these tools as containers and will expect Dockerfiles to assist in doing this for publishing images to their own container registries (i.e. Amazon ECR/ Github GCR) and deployed to their container platforms (i.e. ECS/K8s) with Task Definitions and Helm Charts.

### Solution/User Experience

Develop Dockerfiles for existing AMI-based features and develop project structure and contributing guidelines for community additions.

**Comment by henrykie** [comment]
@kylesomers I think the scope on this is a little wide. We need to clarify which assets we are referring to. Are we suggesting that we want containerized build nodes for C++ compilation? containerized version of Perforce Helix Core?
